name: Create Release Pull Request
on:
  push:
    branches: [main]
jobs:
  release-pull-request:
    permissions:
      pull-requests: write
      contents: write  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - run: gem install --no-document git-pr-release
      - run: git-pr-release
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: prd
          GIT_PR_RELEASE_BRANCH_STAGING: main
          GIT_PR_RELEASE_LABELS: release
          GIT_PR_RELEASE_TEMPLATE: .github/git-pr-release.erb
          TZ: Asia/Tokyo
